CREATE SCHEMA IF NOT EXISTS yth;

CREATE TABLE IF NOT EXISTS yth.trip_app_state (
    state_key VARCHAR(64) PRIMARY KEY,
    state_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
